notifications:
  email: false

language: cpp

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - gdb
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9
      - liblapack-dev
      - clang-3.8

branches:
  only:
    - master
    - kaldi_52

before_install:
  - cat /proc/sys/kernel/core_pattern
  - export XROOT=~/xroot
  - tools/extras/travis_install_bindeps.sh $XROOT

script:
  - CXX=clang++-3.8
    CFLAGS="-march=native"
    LDFLAGS="-llapack"
    INCDIRS="$XROOT/usr/include"
    LIBDIRS="$XROOT/usr/lib"
      tools/extras/travis_script.sh

after_failure:
  - tools/extras/travis_show_failures.sh
