notifications:
  email: false

language: cpp

cache:
  directories:
  - $HOME/.ccache

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - gdb
      - g++-4.9
      - gfortran-4.9
      - liblapack-dev
      - clang-3.8
      - sox

branches:
  only:
    - master
    - pybind11

before_install:
  - cat /proc/sys/kernel/core_pattern
  - export XROOT=~/xroot
  - tools/extras/travis_install_bindeps.sh $XROOT
  - export PATH=$XROOT/usr/bin:$PATH

before_script:
  - which ccache
  - ccache --version
  - ccache --show-stats
  - ccache --zero-stats --max-size=3G

env:
  - CI_TARGETS="all ext"        # Job1: Build everything.
  - CI_TARGETS="test"           # Job2: Test libraries. #### ext_test? adds 5min compile, runs 1 test.

script:
  # See http://petereisentraut.blogspot.com/2011/05/ccache-and-clang.html and
  # http://peter.eisentraut.org/blog/2014/12/01/ccache-and-clang-part-3/
  # for the explanation why extra switches needed for clang with ccache.
  - CXX="ccache clang++-3.8 -Qunused-arguments -fcolor-diagnostics -Wno-tautological-compare"
    CFLAGS=""
    LDFLAGS="-llapack -Wl,-fuse-ld=gold"
    INCDIRS="$XROOT/usr/include"
    LIBDIRS="$XROOT/usr/lib"
      tools/extras/travis_script.sh
#   To troubleshoot cache, add to above: CI_TARGETS=util CCACHE_LOGFILE=~/ccache.log

before_cache:
  - ccache --show-stats

after_failure:
  - tools/extras/travis_show_failures.sh
